# This file contains the different endpoints your bot can use.

action_endpoint:
 url: "http://192.168.1.7:5055/webhook" # Requires the IP of the device running the action server (Putting 'localhost' does not work even if it is being run locally)
 
