version: '3.1'
services:
  do-voice-stt-service:
    image: dsi-icl/do-voice-stt-service:latest
    container_name: do-voice-stt-service
    build: stt_service/
    ports:
      - "3000:3000"
    volumes:
      - "./stt_service/config/config.json:/app/config/config.json:ro"

  do-voice-tts-service:
    image: dsi-icl/do-voice-tts-service:latest
    container_name: do-voice-tts-service
    build: tts_service/
    ports:
      - "5000:5000"
    volumes:
      - "./tts_service/config/config.json:/app/config/config.json:ro"

  do-voice-assistant-service:
    image: dsi-icl/do-voice-assistant-service:latest
    container_name: do-voice-assistant-service
    build: voice_assistant_service/
    ports:
      - "2000:2000"
    volumes:
      - "./voice_assistant_service/config/config.docker.json:/app/config/config.json:ro"

  do-voice-dialog-manager-service:
    image: rasa/rasa:1.10.11-full
    ports:
      - "5005:5005"
    volumes:
      - ./dialog_manager_service/models:/app/models:ro
      - ./dialog_manager_service/config/credentials.docker.yml:/app/config/credentials.yml:ro
      - ./dialog_manager_service/config/endpoints.docker.yml:/app/config/endpoints.yml:ro
    command: ["run","-m","/app/models","--endpoints","/app/config/endpoints.yml","--credentials","/app/config/credentials.yml"]

  do-voice-dialog-manager-actions-service:
    image: dsi-icl/do-voice-dialog-manager-actions-service:latest
    container_name: do-voice-dialog-manager-service
    build: dialog_manager_service/
    ports:
      - "5055:5055"
